Flutter 3.0.0
mateusfccp/update_available pull request #15
Opened 2022-10-14 08:35 UTC by otopba

2022-10-14 09:15 UTC, mateusfccp commented
Hello, @otopba.

I am failing to understand what this PR does. It includes a lot of formatting changes, which is making hard to know what has indeed changed or not.

Could you clean this PR so that it respects the current code formatting configuration?

Also, could you provide more information regarding what does this PR proposes? It seems that it's related to Flutter 3.0, but this plugin should work fine with Flutter 3.0. Did you find any issue using it with Flutter 3.0?

2022-10-14 09:18 UTC, otopba commented
Hello!
In this PR I updated all the dependencies and cleaned up the project =)
Applied code style

2022-10-14 10:14 UTC, mateusfccp commented
I don't think the code style changes are necessary. I will kindly ask you to revert them. IMO, the current formatting is better, and it did not cause any issues with `pana` nor anything.

2022-10-14 10:16 UTC, mateusfccp requested changes

2022-10-14 10:16 UTC, mateusfccp commented on update_available/pubspec.yaml
> +  flutter: ">=3.0.0"
Do we have to break? I don't see any reason to require Flutter 3.0 if it already works with Flutter 3.0 and is also backwards compatible.

2022-10-21 10:56 UTC, otopba commented
@mateusfccp 

Hi!
I really went a little overboard with the changes. Actually, all I had to do was upgrade package_info_plus to 3.0.1

2022-12-06 09:08 UTC, mateusfccp commented
I am going to give some attention to the issues and PRs when my vacations start, which is 15/Dec.

2022-12-26 21:27 UTC, mateusfccp commented
@otopba Could you rebase to the latest master? Now that #19 is merged we should not have any problem in the checks.

2022-12-29 10:24 UTC, otopba commented on update_available/pubspec.yaml
> +  flutter: ">=3.0.0"
Out of date

2022-12-29 10:24 UTC, otopba commented
@mateusfccp fixed

2022-12-29 10:28 UTC, mateusfccp approved these changes

2022-12-29 10:28 UTC, merged