Bump required min SDK and add CI check
mateusfccp/update_available pull request #20
Opened 2022-12-05 13:35 UTC by kuhnroyal

* required due to `meta: ^1.7.0` dependency
* required due to invalid plugin registrations prior to Flutter 2.8.0

2022-12-25 18:45 UTC, mateusfccp commented
@kuhnroyal
It seems `meta: 1.7.0` requires Dart 2.12, which is available since Flutter 2.0.
https://github.com/dart-lang/sdk/blob/5b39eb2f0183fde63ae7d7851e8bfaf6a4075998/pkg/meta/pubspec.yaml

Thus, I'm failing to understanding the objective of this PR. Could you clarify?

2022-12-25 18:54 UTC, kuhnroyal commented
Flutter versions prior 2.8.0 use an older meta version (1.3.0 I think). Since this package forces 1.7.0, you have to use min Flutter 2.8.0.

2022-12-26 21:11 UTC, mateusfccp commented
Yeah, I didn't want to break this package for <3, but it seems it's already broken for <2.8. I will accept your PR and release a last 2 versions (2.2) with these changes. Then, release a new breaking for Flutter 3.

2022-12-26 21:16 UTC, mateusfccp requested changes

2022-12-26 21:16 UTC, mateusfccp commented on update_available/example/android/app/build.gradle
> +        targetSdkVersion 31
Is this change necessary?

2022-12-26 21:16 UTC, mateusfccp commented on update_available/example/android/app/build.gradle
> +    compileSdkVersion 31
Is this change necessary?

2022-12-26 21:16 UTC, mateusfccp commented on .github/workflows/main.yml
> +      - run: flutter pub get
I think it's enough to simply specify the version 2.8.0 in all the jobs, as they already run `flutter pub get`. At least locally, this worked.

2022-12-26 21:16 UTC, mateusfccp commented on .github/workflows/main.yml
> +    - run: flutter format -o show -l 200 -- set-exit-if-changed .
Is this change necessary?

2022-12-26 22:30 UTC, kuhnroyal commented on .github/workflows/main.yml
> +    - run: flutter format -o show -l 200 -- set-exit-if-changed .
No this should not be here

2022-12-26 22:56 UTC, kuhnroyal commented on .github/workflows/main.yml
> +      - run: flutter pub get
Running the normal build against `stable` allows to notice if something new in Dart/Flutter breaks the package.
Running a step against the min. supported version ensures that changes that break the min. version get noticed.
I would leave this as is.

2022-12-26 22:57 UTC, kuhnroyal commented on update_available/example/android/app/build.gradle
> +        targetSdkVersion 31
Not really, but 29 is the absolute minimum atm. for target SDK in the Play store.
Bumping this is just housekeeping.

2022-12-26 23:49 UTC, mateusfccp commented on update_available/example/android/app/build.gradle
> +        targetSdkVersion 31
Please, open a different PR for this, as this one concerns the version issue

2023-01-09 22:40 UTC, merged