iOS version: force itunes to unvalidate its cache
mateusfccp/update_available pull request #45
Opened 2024-08-26 08:04 UTC by millerf

Fixes #44 

Forces Itunes to invalidate its cache and prevent sending outdated version.

2024-08-26 12:08 UTC, mateusfccp commented
I looked at how `upgrader` do, and they also use a "cache buster" (as they call).

I think their approach is more sensible, as it's virtually impossible to have the same code generated. They used `DateTime` to get the current timestamp.

You can see it here:

https://github.com/larryaasen/upgrader/blob/fa02d08e4d68dd43f4c0392f093ac609c744e453/lib/src/itunes_search_api.dart#L131

2024-08-26 12:10 UTC, mateusfccp requested changes

2024-08-26 12:10 UTC, mateusfccp commented on update_available_ios/lib/adapters/get_ios_package_version_impl.dart
> -
Not related to the PR, please revert.

2024-08-26 12:10 UTC, mateusfccp commented on update_available_ios/lib/adapters/get_ios_package_version_impl.dart
> +    Random random = new Random();
```suggestion
    final random = Random();
```

2024-08-26 12:10 UTC, mateusfccp commented on update_available_ios/lib/adapters/get_ios_package_version_impl.dart
> +    int randomNumber = random.nextInt(1000);
```suggestion
    final randomNumber = random.nextInt(1000);
```

2024-08-26 12:17 UTC, millerf commented
> I looked at how `upgrader` do, and they also use a "cache buster" (as they call).
> 
> I think their approach is more sensible, as it's virtually impossible to have the same code generated. They used `DateTime` to get the current timestamp.
> 
> You can see it here:
> 
> https://github.com/larryaasen/upgrader/blob/fa02d08e4d68dd43f4c0392f093ac609c744e453/lib/src/itunes_search_api.dart#L131

Sorry this was not properly written. When I realised it was somewhat hacky, I did not push it too much.
If you think you want to land this "cache custer"  approach, I'll definitely clean it.

2024-08-26 12:20 UTC, mateusfccp commented
> > I looked at how `upgrader` do, and they also use a "cache buster" (as they call).
> > I think their approach is more sensible, as it's virtually impossible to have the same code generated. They used `DateTime` to get the current timestamp.
> > You can see it here:
> > https://github.com/larryaasen/upgrader/blob/fa02d08e4d68dd43f4c0392f093ac609c744e453/lib/src/itunes_search_api.dart#L131
> 
> Sorry this was not properly written. When I realised it was somewhat hacky, I did not push it too much. If you think you want to land this "cache custer" approach, I'll definitely clean it.

I wouldn't call it exactly hacky. I don't know why it's being cached, but this approach is something that's actually used a lot in web development to prevent browser caching.

However, I think using `DateTime` instead of `Random` is a more reasonable approach. If you can implement it this way, I'll be glad to merge your MR.

2024-08-26 12:24 UTC, millerf commented
> I wouldn't call it exactly hacky. I don't know why it's being cached, but this approach is something that's actually used a lot in web development to prevent browser caching.

I know, however bypassing a server's cache could have more unforeseen issues (such as being blacklisted). But I guess in that case it does not really matter.

I implemented the change and used a timestamp, which is evidently a better approach.

2024-08-26 13:05 UTC, mateusfccp requested changes

2024-08-26 13:05 UTC, mateusfccp commented on update_available_ios/lib/adapters/get_ios_package_version_impl.dart
> +    final String timeStamp = DateTime.now().millisecondsSinceEpoch.toString();
```suggestion
    final timestamp = DateTime.now().millisecondsSinceEpoch;
```

* Timestamp is a single word, so the correct capitalization would be `timestamp`;
* This repository follows Effective Dart, which says "local variables shouldn't have type annotations and should be declared using just `var` or `final`";
* `toString()` is not necessary here, since string interpolation implicitly calls it.

2024-08-26 13:05 UTC, mateusfccp commented on update_available_ios/lib/adapters/get_ios_package_version_impl.dart
> +    final String timeStamp = DateTime.now().millisecondsSinceEpoch.toString();
Change the other occurrences of `timeStamp` to `timestamp` too.

2024-08-26 13:41 UTC, millerf commented
> Please, add a `## Unreleased` version to the changelogs with this change described and pointing to the issue

Done.

2024-08-26 13:42 UTC, millerf commented
Feel free to update the changelog description to your liking :)

2024-08-26 13:57 UTC, mateusfccp commented
A test has failed, can you please have a look?

2024-08-26 14:02 UTC, millerf commented
@mateusfccp Tests are passing locally. URL called is https://itunes.apple.com/lookup?bundleId=org.adventistas.armsa&_=1724680668385 and works fine.
I'll restart them with an empty commit.

2024-08-26 14:57 UTC, mateusfccp approved these changes

2024-08-26 14:57 UTC, mateusfccp commented
@millerf LGTM, can you sign your commits as required by the branch rules?

2024-08-26 21:32 UTC, millerf commented
@mateusfccp Done. Sorry I have been busy...

2024-08-26 21:59 UTC, mateusfccp commented
No problem, thanks for your contribution.

2024-08-26 21:59 UTC, merged

2024-08-28 10:27 UTC, millerf commented
@mateusfccp Could you deploy the new version on flutter.dev when you get a chance?

2024-08-28 11:20 UTC, mateusfccp commented
> @mateusfccp Could you deploy the new version on flutter.dev when you get a chance?

Yes, I would like to solve #43 before doing it, but I'm not sure if I'll be able to do it immediately.

2024-08-28 11:27 UTC, millerf commented
> > @mateusfccp Could you deploy the new version on flutter.dev when you get a chance?
> 

I see! No worries. I can still override the repo with my branch if needed. No rush.

2024-09-10 23:22 UTC, millerf commented
Please let me know when this is available, so I can remove my override ;)

2024-09-30 13:05 UTC, mateusfccp commented
As #43 is not being resolved as soon as I though, I am going to make a release with this.

2024-09-30 13:12 UTC, mateusfccp commented
@millerf, released version 3.2.0